language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"
 # both of these targets complain about exist_ok in makedirs()
 # but I don't really if my code runs in 2.7 anyway.
 #- "2.7"
 #- "pypy"
script:
 - "behave"
 - "pytest"
