language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"
 # both of these targets complain about exist_ok in makedirs()
 # but I don't really if my code runs in 2.7 anyway.
 #- "2.7"
 #- "pypy"
script:
# I know that I need to rethink my behave test suite, so for the moment
# I don't want to see Travis builds failing because of it.
# - "behave"
 - "pytest"
