language: python
python:
# For now let's just get 3.6 working.
# - "2.7"
# - "3.5"
 - "3.6"
script:
 - "behave"
 # For now it's looking for testbed files that maybe shouldn't be under git
 #- "pytest"
